### ISSUE TITLE
Plugin Request

### ISSUE THREAD

**Issue by Wikinger8** [D3SOX/vencord-userplugins#17]
I dont know if you also do some requests but I found some cool plugin ideas from an [old Betterdiscord](https://github.com/YofukashiNo/BetterDiscordPlugins/blob/master/DiscordBypasses.plugin.js) plugin.

**No push to talk:** Lets you use voice activity in channels that enforce the use of push-to-talk.

**Custom stream preview:** Image to render as stream preview.

**No Idle:** Stops Discord from setting your presence to idle.

**Guild Verification Bypass:** Removes the 10 minutes wait before being able to join voice channels in newly joined guilds. (Maybe it is not needed if you are phone verified but dont know)

I think [this](https://github.com/YofukashiNo/DiscordBypasses) is also the updated plugin for replugged dont know if that helps.

**Comment by D3SOX** [comment]
I think you're better off requesting those on https://github.com/Vencord/plugin-requests/issues because more devs have their eyes on there.
I kinda just do plugins I would use myself and I don't really have a need for those
