### ISSUE TITLE
VoiceChatUtilities

### ISSUE THREAD

**Issue by Wikinger8** [D3SOX/vencord-userplugins#18]
I know it is better to have the RestApi but would be very cool to have a toggle or something in the settings to do everything **instant**.
I also tried to remove the [* 500](https://github.com/D3SOX/vencord-userplugins/blob/a3f9f856e969da00907836144969e6f51ed225a8/voiceChatUtilities/index.tsx#L29) but still not instant :(

**Comment by D3SOX** [comment]
I know the way it currently works is not perfect, but I don't think we can bypass the rate limit

**Comment by D3SOX** [comment]
Should be way faster now

**Comment by D3SOX** [comment]
Could you maybe confirm this?
