### ISSUE TITLE
NotifyUserChanges Suggestions

### ISSUE THREAD

**Issue by unoriginals** [D3SOX/vencord-userplugins#20]
Love the plugin but would love some improvements!

1. Allow the notifications to count down without Discord needed to be focused, or add a setting for this.
2. Add a log for the notifications.
3. Add detection/notifications for status changes/activity changes, (game changes, spotify song changes, custom status changes, etc)
4. If possible, I'm new to vencord, make the notification a bit more aesthetically pleasing, slick, and clean.
5. Add a setting to automatically notify for all friends instead of doing people individually

**Comment by D3SOX** [comment]
(1) (4) Notifications are a Vencord feature. If you want to get them improved request it there.
(2) There is already a notification log. I can make it configurable if they should stay in the log.
(5) (3) As for the feature requests, please read the README inside the plugin folder. It's not meant to be a stalker plugin
