### ISSUE TITLE
[Bug] Ur plugins won't load. :(

### ISSUE THREAD

**Issue by Soulivan71** [D3SOX/vencord-userplugins#29]
Im using this discord version :
canary 290439 (7e1011c) Host 1.0.340 x64 (47455) Windows 10 64-bit (10.0.19045)

https://github.com/D3SOX/vencord-userplugins/assets/36502190/d757deed-c03a-440a-a510-5825e753d901

Then In my plugin folder ur plugin won't appear and work 😭

**Comment by D3SOX** [comment]
Firstly Canary is not supported, use stable
Try to search for errors in the Discord console with CTRL + Shift + I

**Comment by Soulivan71** [comment]
> Firstly Canary is not supported, use stable Try to search for errors in the Discord console with CTRL + Shift + I

I need to do pnpm build in folder first then launch discord ?

**Comment by D3SOX** [comment]
And the plugins just don't appear? Can you try and confirm if it happens with stable too?

**Comment by Soulivan71** [comment]
Yeah don't appear

**Comment by Soulivan71** [comment]
On Stable aswell and I have vencord

**Comment by Soulivan71** [comment]
So vencord issue ?

**Comment by D3SOX** [comment]
I wouldn't say it's an issue of Vencord itself, probably just your configuration. I'm still not sure why this happens to you, would need more information

**Comment by D3SOX** [comment]
Inside `D3SOX-userplugins` is an `index.ts` file right?

**Comment by Soulivan71** [comment]
The otherr pl : won't load too 
![image](https://github.com/D3SOX/vencord-userplugins/assets/36502190/2c4d557a-2399-404d-b52b-375834a57f9f)
Yeah I hav e the index.ts

**Comment by Soulivan71** [comment]
I finally get my solution thx anyway !

**Comment by D3SOX** [comment]
Can you post the solution if someone else has the same problem?

**Comment by Soulivan71** [comment]
I need to redo the installation of veencord...
