### ISSUE TITLE
[Bug] Notifications

### ISSUE THREAD

**Issue by Soulivan71** [D3SOX/vencord-userplugins#30]
![image](https://github.com/D3SOX/vencord-userplugins/assets/36502190/4aae1b77-e899-4092-b95d-9f54a55e16d8)
Hello sry again but is it from u ?
(Im using twoscreens) and this goes to every game Im focused on (first screen & snd screen too)
First notification goes away but the other one no.
And happened after resting pc, discord app etc

**Comment by Soulivan71** [comment]
Its fixed itself when I got new one so idk whats the issue

**Comment by Soulivan71** [comment]
Ok so Im still having issue its little annoying... (I have multiple instance of game) if this can help u 
Its seem to happend when I switch on different games and the blue time bar doesn't finish

**Comment by D3SOX** [comment]
Vencord issue, not my plugins

**Comment by Soulivan71** [comment]
> Vencord issue, not my plugins. Use support channel

They are going to fix knowing issue or I need to make a support post ?

**Comment by D3SOX** [comment]
The support channel on the Vencord server is the first place to report issues
https://vencord.dev/discord

**Comment by Soulivan71** [comment]
Can u please doing for me ? Cause Im not on

**Comment by D3SOX** [comment]
I don't have this issue so it doesn't really make sense for me to ask because if there are questions I would always need to ask you back. Just join the server

**Comment by Soulivan71** [comment]
![image](https://github.com/D3SOX/vencord-userplugins/assets/36502190/b10dd8e6-2dfd-44e2-8328-e07e3708c68b)
Issue from ur side.

**Comment by Soulivan71** [comment]
Btw the first notification on top its from toastnotificatioon I guess.
https://github.com/Vendicated/Vencord/pull/1806
This can maybe help u to find problem, idk

**Comment by Soulivan71** [comment]
I turn off ur plugin and then the notification is properly running away

**Comment by D3SOX** [comment]
> Btw the first notification on top its from toastnotificatioon I guess. [Vendicated/Vencord#1806](https://github.com/Vendicated/Vencord/pull/1806) This can maybe help u to find problem, idk

Then it's an issue with the ToastNotifications plugin you're using, as it's not happening without it or is it?

**Comment by Soulivan71** [comment]
Happening with ur plugin.

**Comment by D3SOX** [comment]
As you didn't answer my question, I'm gonna lock this now. It doesn't matter if it happens with my plugin. It just sends notifications. I did not implement notifications myself.
