### ISSUE TITLE
Build failed with 1 error: must contain definePlugin call with simple string name property as first property

### ISSUE THREAD

**Issue by Chaython** [D3SOX/vencord-userplugins#38]
`Build failed with 1 error:
node_modules/.pnpm/esbuild@0.15.18/node_modules/esbuild/lib/main.js:1397:21: ERROR: [plugin: glob-natives-plugin] Invalid plugin src\userplugins\D3SOX-userplugin: must contain definePlugin call with simple string name property as first property`

**Comment by floppy-wip** [comment]
> `Build failed with 1 error: node_modules/.pnpm/esbuild@0.15.18/node_modules/esbuild/lib/main.js:1397:21: ERROR: [plugin: glob-natives-plugin] Invalid plugin src\userplugins\D3SOX-userplugin: must contain definePlugin call with simple string name property as first property`


same problem when updating from app or building
![Captura de pantalla 2024-06-22 110916](https://github.com/D3SOX/vencord-userplugins/assets/61437168/7e998a3b-7872-4138-968a-af2440015b2b)

**Comment by D3SOX** [comment]
No idea why this is suddenly happening to you but I think I have seen a similar error message recently. I'm currently on vacation so I can only fix this at the end of next week unless someone creates a PR

**Comment by Lust-Ware** [comment]
same problem here, only happens with your plugins, if i try to build when removing your plugins, no error.

clone brand new from your github, same error

**Comment by D3SOX** [comment]
I think I found the culprit.
Can anybody try reverting this commit https://github.com/Vendicated/Vencord/commit/c7e4bec94099e9f92a4402e56a87214e8817b053 locally or try to add
```ts
import definePlugin from "@utils/types";
export default definePlugin({name:"dummy"})
``` inside `native/index.ts`

**Comment by BLACK4585** [comment]
Hey,
I added your suggestion and also added the required fields but I still get the error.
The file looks like this now:
```
/*
 * Vencord, a Discord client mod
 * Copyright (c) 2024 Vendicated and contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import definePlugin from "@utils/types";
export default definePlugin({
    name: "dummy",
    description: "",
    authors: []
});

export * from "./updater";

// so we can filter the native helpers by this key
export function d3soxUpdaterUniqueIdThingyIdkMan() { }
```

**Comment by D3SOX** [comment]
I have temporarily removed the updater so it should work with manual updates for the time being. Don't be scared if it still prints the error you should see the plugins now.

**Comment by D3SOX** [comment]
> I think I found the culprit.
> Can anybody try reverting this commit https://github.com/Vendicated/Vencord/commit/c7e4bec94099e9f92a4402e56a87214e8817b053 locally (`git revert c7e4bec94099e9f92a4402e56a87214e8817b053`) 
> 
> and see if it builds

Btw this makes it work with the updater but it's not a really a good solution. Really annoying they had to change that..

**Comment by RobinRMC** [comment]
I'm still having the issue.

**Comment by D3SOX** [comment]
I'm unable to fix this an Vencord's new unofficial plugins only allow one plugin per repo so for everybody who want's to continue using my plugins see the [new README](https://github.com/D3SOX/vencord-userplugins?tab=readme-ov-file#unsupported)

**Comment by D3SOX** [comment]
See #40
