### ISSUE TITLE
Reinstantiate userplugins repo

### ISSUE THREAD

**Issue by RobinRMC** [D3SOX/vencord-userplugins#40]
Regarding [D3SOX/vencord-userplugins](https://github.com/D3SOX/vencord-userplugins):

It's still possible to have multiple userplugins in one repository. [Kyuuhachi/VencordPlugins](https://github.com/Kyuuhachi/VencordPlugins) still works fine.

Could you look into this?

**Comment by D3SOX** [comment]
I guess it's not worth the effort creating a script now that I already have them in separate repos. See the updated README
