### ISSUE TITLE
MemberListActivities: "Crunchyroll" Icon spam for 'single' activity

### ISSUE THREAD

**Issue by jaxellis** [D3SOX/vencord-userplugins#5]
This application has multiple activities that are the exact same which causes some icon spam to happen.
![image](https://github.com/D3SOX/vencord-userplugins/assets/67706810/17443ec3-0a88-49ee-a517-43ab2e09659f)
![image](https://github.com/D3SOX/vencord-userplugins/assets/67706810/1e90b74f-6fed-4500-b506-77248e1b806d)

Might have to create a check for multiple of the same icons and only add 1 of them. 

Users who use [Premid](https://premid.app/) also have 2 twitch icons when on twitch, one from the premid application and the icon from this repo.

**Comment by D3SOX** [comment]
I've also seen people using [WatchDis](https://watchdis.tv/) having many icons but this seems to be because of poor code as the user actually has that many activities that are also shown when you go to the activities tab on the profile modal.

Anyways, your PR is definitely good to have
